# Generated by Django 3.1.6 on 2021-03-07 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_publishinghouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishinghouse',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='publish_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='p_library.publishinghouse'),
        ),
    ]
