# Generated by Django 3.1.6 on 2021-03-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20210307_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish_house',
            new_name='publishing_house',
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
